/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhatsappConnectRouteImport } from './routes/whatsapp.connect'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProspekRouteImport } from './routes/_app/prospek'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppOpportunityRouteImport } from './routes/_app/opportunity'
import { Route as AppNotifikasiRouteImport } from './routes/_app/notifikasi'
import { Route as AppMetricsRouteImport } from './routes/_app/metrics'
import { Route as AppLogAktivitasRouteImport } from './routes/_app/log-aktivitas'
import { Route as AppKnowledgeRouteImport } from './routes/_app/knowledge'
import { Route as AppIntegrationRouteImport } from './routes/_app/integration'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppHandoverRouteImport } from './routes/_app/handover'
import { Route as AppFlowsRouteImport } from './routes/_app/flows'
import { Route as AppDealsRouteImport } from './routes/_app/deals'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppBroadcastRouteImport } from './routes/_app/broadcast'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAiAgentsRouteImport } from './routes/_app/ai-agents'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppTasksIndexRouteImport } from './routes/_app/tasks/index'
import { Route as AppSalesProfilesIndexRouteImport } from './routes/_app/sales-profiles/index'
import { Route as AppSaktiIndexRouteImport } from './routes/_app/sakti/index'
import { Route as AppKelolaTimIndexRouteImport } from './routes/_app/kelola-tim/index'
import { Route as AppDevelopersIndexRouteImport } from './routes/_app/developers/index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppCompaniesIndexRouteImport } from './routes/_app/companies/index'
import { Route as AppAlihTugasIndexRouteImport } from './routes/_app/alih-tugas/index'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app/tasks/$taskId'
import { Route as AppSalesProfilesUserIdRouteImport } from './routes/_app/sales-profiles/$userId'
import { Route as AppSaktiSuratBaruRouteImport } from './routes/_app/sakti/surat-baru'
import { Route as AppKelolaTimUserIdRouteImport } from './routes/_app/kelola-tim/$userId'
import { Route as AppFlowsFlowIdRouteImport } from './routes/_app/flows/$flowId'
import { Route as AppDevelopersWebhooksRouteImport } from './routes/_app/developers/webhooks'
import { Route as AppDevelopersMessagesSentByApiRouteImport } from './routes/_app/developers/messages-sent-by-api'
import { Route as AppDevelopersApiToolsRouteImport } from './routes/_app/developers/api-tools'
import { Route as AppDevelopersApiDocumentationRouteImport } from './routes/_app/developers/api-documentation'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app/customers/$customerId'
import { Route as AppCompaniesCompanyIdRouteImport } from './routes/_app/companies/$companyId'
import { Route as AppChannelsWhatsappRouteImport } from './routes/_app/channels/whatsapp'
import { Route as AppChannelsTelegramRouteImport } from './routes/_app/channels/telegram'
import { Route as AppChannelsLivechatRouteImport } from './routes/_app/channels/livechat'
import { Route as AppChannelsLineRouteImport } from './routes/_app/channels/line'
import { Route as AppChannelsFacebookRouteImport } from './routes/_app/channels/facebook'
import { Route as AppChannelsCustomRouteImport } from './routes/_app/channels/custom'
import { Route as AppChannelsBotRouteImport } from './routes/_app/channels/bot'
import { Route as AppAppsMetaAdsTrackerRouteImport } from './routes/_app/apps/meta-ads-tracker'
import { Route as AppAlihTugasConversationIdRouteImport } from './routes/_app/alih-tugas/$conversationId'
import { Route as AppAiAgentsAgentIdRouteImport } from './routes/_app/ai-agents/$agentId'
import { Route as AppDevelopersApiToolsNewRouteImport } from './routes/_app/developers/api-tools/new'
import { Route as AppChannelsWhatsappSuccessRouteImport } from './routes/_app/channels/whatsapp/success'
import { Route as AppChannelsWhatsappChannelIdRouteImport } from './routes/_app/channels/whatsapp/$channelId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappConnectRoute = WhatsappConnectRouteImport.update({
  id: '/whatsapp/connect',
  path: '/whatsapp/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProspekRoute = AppProspekRouteImport.update({
  id: '/prospek',
  path: '/prospek',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunityRoute = AppOpportunityRouteImport.update({
  id: '/opportunity',
  path: '/opportunity',
  getParentRoute: () => AppRoute,
} as any)
const AppNotifikasiRoute = AppNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any)
const AppLogAktivitasRoute = AppLogAktivitasRouteImport.update({
  id: '/log-aktivitas',
  path: '/log-aktivitas',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationRoute = AppIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppHandoverRoute = AppHandoverRouteImport.update({
  id: '/handover',
  path: '/handover',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsRoute = AppFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AppRoute,
} as any)
const AppDealsRoute = AppDealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastRoute = AppBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAgentsRoute = AppAiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesProfilesIndexRoute = AppSalesProfilesIndexRouteImport.update({
  id: '/sales-profiles/',
  path: '/sales-profiles/',
  getParentRoute: () => AppRoute,
} as any)
const AppSaktiIndexRoute = AppSaktiIndexRouteImport.update({
  id: '/sakti/',
  path: '/sakti/',
  getParentRoute: () => AppRoute,
} as any)
const AppKelolaTimIndexRoute = AppKelolaTimIndexRouteImport.update({
  id: '/kelola-tim/',
  path: '/kelola-tim/',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersIndexRoute = AppDevelopersIndexRouteImport.update({
  id: '/developers/',
  path: '/developers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesIndexRoute = AppCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlihTugasIndexRoute = AppAlihTugasIndexRouteImport.update({
  id: '/alih-tugas/',
  path: '/alih-tugas/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesProfilesUserIdRoute = AppSalesProfilesUserIdRouteImport.update({
  id: '/sales-profiles/$userId',
  path: '/sales-profiles/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppSaktiSuratBaruRoute = AppSaktiSuratBaruRouteImport.update({
  id: '/sakti/surat-baru',
  path: '/sakti/surat-baru',
  getParentRoute: () => AppRoute,
} as any)
const AppKelolaTimUserIdRoute = AppKelolaTimUserIdRouteImport.update({
  id: '/kelola-tim/$userId',
  path: '/kelola-tim/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowsFlowIdRoute = AppFlowsFlowIdRouteImport.update({
  id: '/$flowId',
  path: '/$flowId',
  getParentRoute: () => AppFlowsRoute,
} as any)
const AppDevelopersWebhooksRoute = AppDevelopersWebhooksRouteImport.update({
  id: '/developers/webhooks',
  path: '/developers/webhooks',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersMessagesSentByApiRoute =
  AppDevelopersMessagesSentByApiRouteImport.update({
    id: '/developers/messages-sent-by-api',
    path: '/developers/messages-sent-by-api',
    getParentRoute: () => AppRoute,
  } as any)
const AppDevelopersApiToolsRoute = AppDevelopersApiToolsRouteImport.update({
  id: '/developers/api-tools',
  path: '/developers/api-tools',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersApiDocumentationRoute =
  AppDevelopersApiDocumentationRouteImport.update({
    id: '/developers/api-documentation',
    path: '/developers/api-documentation',
    getParentRoute: () => AppRoute,
  } as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesCompanyIdRoute = AppCompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsWhatsappRoute = AppChannelsWhatsappRouteImport.update({
  id: '/channels/whatsapp',
  path: '/channels/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsTelegramRoute = AppChannelsTelegramRouteImport.update({
  id: '/channels/telegram',
  path: '/channels/telegram',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsLivechatRoute = AppChannelsLivechatRouteImport.update({
  id: '/channels/livechat',
  path: '/channels/livechat',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsLineRoute = AppChannelsLineRouteImport.update({
  id: '/channels/line',
  path: '/channels/line',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsFacebookRoute = AppChannelsFacebookRouteImport.update({
  id: '/channels/facebook',
  path: '/channels/facebook',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsCustomRoute = AppChannelsCustomRouteImport.update({
  id: '/channels/custom',
  path: '/channels/custom',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsBotRoute = AppChannelsBotRouteImport.update({
  id: '/channels/bot',
  path: '/channels/bot',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsMetaAdsTrackerRoute = AppAppsMetaAdsTrackerRouteImport.update({
  id: '/apps/meta-ads-tracker',
  path: '/apps/meta-ads-tracker',
  getParentRoute: () => AppRoute,
} as any)
const AppAlihTugasConversationIdRoute =
  AppAlihTugasConversationIdRouteImport.update({
    id: '/alih-tugas/$conversationId',
    path: '/alih-tugas/$conversationId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAiAgentsAgentIdRoute = AppAiAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AppAiAgentsRoute,
} as any)
const AppDevelopersApiToolsNewRoute =
  AppDevelopersApiToolsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppDevelopersApiToolsRoute,
  } as any)
const AppChannelsWhatsappSuccessRoute =
  AppChannelsWhatsappSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => AppChannelsWhatsappRoute,
  } as any)
const AppChannelsWhatsappChannelIdRoute =
  AppChannelsWhatsappChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => AppChannelsWhatsappRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/ai': typeof AppAiRoute
  '/ai-agents': typeof AppAiAgentsRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/broadcast': typeof AppBroadcastRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/deals': typeof AppDealsRoute
  '/flows': typeof AppFlowsRouteWithChildren
  '/handover': typeof AppHandoverRoute
  '/help': typeof AppHelpRoute
  '/import': typeof AppImportRoute
  '/integration': typeof AppIntegrationRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/log-aktivitas': typeof AppLogAktivitasRoute
  '/metrics': typeof AppMetricsRoute
  '/notifikasi': typeof AppNotifikasiRoute
  '/opportunity': typeof AppOpportunityRoute
  '/pipeline': typeof AppPipelineRoute
  '/prospek': typeof AppProspekRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/whatsapp/connect': typeof WhatsappConnectRoute
  '/ai-agents/$agentId': typeof AppAiAgentsAgentIdRoute
  '/alih-tugas/$conversationId': typeof AppAlihTugasConversationIdRoute
  '/apps/meta-ads-tracker': typeof AppAppsMetaAdsTrackerRoute
  '/channels/bot': typeof AppChannelsBotRoute
  '/channels/custom': typeof AppChannelsCustomRoute
  '/channels/facebook': typeof AppChannelsFacebookRoute
  '/channels/line': typeof AppChannelsLineRoute
  '/channels/livechat': typeof AppChannelsLivechatRoute
  '/channels/telegram': typeof AppChannelsTelegramRoute
  '/channels/whatsapp': typeof AppChannelsWhatsappRouteWithChildren
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/developers/api-documentation': typeof AppDevelopersApiDocumentationRoute
  '/developers/api-tools': typeof AppDevelopersApiToolsRouteWithChildren
  '/developers/messages-sent-by-api': typeof AppDevelopersMessagesSentByApiRoute
  '/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/kelola-tim/$userId': typeof AppKelolaTimUserIdRoute
  '/sakti/surat-baru': typeof AppSaktiSuratBaruRoute
  '/sales-profiles/$userId': typeof AppSalesProfilesUserIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/alih-tugas/': typeof AppAlihTugasIndexRoute
  '/companies/': typeof AppCompaniesIndexRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/developers/': typeof AppDevelopersIndexRoute
  '/kelola-tim/': typeof AppKelolaTimIndexRoute
  '/sakti/': typeof AppSaktiIndexRoute
  '/sales-profiles/': typeof AppSalesProfilesIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
  '/channels/whatsapp/$channelId': typeof AppChannelsWhatsappChannelIdRoute
  '/channels/whatsapp/success': typeof AppChannelsWhatsappSuccessRoute
  '/developers/api-tools/new': typeof AppDevelopersApiToolsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/ai': typeof AppAiRoute
  '/ai-agents': typeof AppAiAgentsRouteWithChildren
  '/analytics': typeof AppAnalyticsRoute
  '/broadcast': typeof AppBroadcastRoute
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/deals': typeof AppDealsRoute
  '/flows': typeof AppFlowsRouteWithChildren
  '/handover': typeof AppHandoverRoute
  '/help': typeof AppHelpRoute
  '/import': typeof AppImportRoute
  '/integration': typeof AppIntegrationRoute
  '/knowledge': typeof AppKnowledgeRoute
  '/log-aktivitas': typeof AppLogAktivitasRoute
  '/metrics': typeof AppMetricsRoute
  '/notifikasi': typeof AppNotifikasiRoute
  '/opportunity': typeof AppOpportunityRoute
  '/pipeline': typeof AppPipelineRoute
  '/prospek': typeof AppProspekRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/whatsapp/connect': typeof WhatsappConnectRoute
  '/ai-agents/$agentId': typeof AppAiAgentsAgentIdRoute
  '/alih-tugas/$conversationId': typeof AppAlihTugasConversationIdRoute
  '/apps/meta-ads-tracker': typeof AppAppsMetaAdsTrackerRoute
  '/channels/bot': typeof AppChannelsBotRoute
  '/channels/custom': typeof AppChannelsCustomRoute
  '/channels/facebook': typeof AppChannelsFacebookRoute
  '/channels/line': typeof AppChannelsLineRoute
  '/channels/livechat': typeof AppChannelsLivechatRoute
  '/channels/telegram': typeof AppChannelsTelegramRoute
  '/channels/whatsapp': typeof AppChannelsWhatsappRouteWithChildren
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/developers/api-documentation': typeof AppDevelopersApiDocumentationRoute
  '/developers/api-tools': typeof AppDevelopersApiToolsRouteWithChildren
  '/developers/messages-sent-by-api': typeof AppDevelopersMessagesSentByApiRoute
  '/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/kelola-tim/$userId': typeof AppKelolaTimUserIdRoute
  '/sakti/surat-baru': typeof AppSaktiSuratBaruRoute
  '/sales-profiles/$userId': typeof AppSalesProfilesUserIdRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/alih-tugas': typeof AppAlihTugasIndexRoute
  '/companies': typeof AppCompaniesIndexRoute
  '/customers': typeof AppCustomersIndexRoute
  '/developers': typeof AppDevelopersIndexRoute
  '/kelola-tim': typeof AppKelolaTimIndexRoute
  '/sakti': typeof AppSaktiIndexRoute
  '/sales-profiles': typeof AppSalesProfilesIndexRoute
  '/tasks': typeof AppTasksIndexRoute
  '/channels/whatsapp/$channelId': typeof AppChannelsWhatsappChannelIdRoute
  '/channels/whatsapp/success': typeof AppChannelsWhatsappSuccessRoute
  '/developers/api-tools/new': typeof AppDevelopersApiToolsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/ai-agents': typeof AppAiAgentsRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/broadcast': typeof AppBroadcastRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deals': typeof AppDealsRoute
  '/_app/flows': typeof AppFlowsRouteWithChildren
  '/_app/handover': typeof AppHandoverRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/import': typeof AppImportRoute
  '/_app/integration': typeof AppIntegrationRoute
  '/_app/knowledge': typeof AppKnowledgeRoute
  '/_app/log-aktivitas': typeof AppLogAktivitasRoute
  '/_app/metrics': typeof AppMetricsRoute
  '/_app/notifikasi': typeof AppNotifikasiRoute
  '/_app/opportunity': typeof AppOpportunityRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/prospek': typeof AppProspekRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/whatsapp/connect': typeof WhatsappConnectRoute
  '/_app/ai-agents/$agentId': typeof AppAiAgentsAgentIdRoute
  '/_app/alih-tugas/$conversationId': typeof AppAlihTugasConversationIdRoute
  '/_app/apps/meta-ads-tracker': typeof AppAppsMetaAdsTrackerRoute
  '/_app/channels/bot': typeof AppChannelsBotRoute
  '/_app/channels/custom': typeof AppChannelsCustomRoute
  '/_app/channels/facebook': typeof AppChannelsFacebookRoute
  '/_app/channels/line': typeof AppChannelsLineRoute
  '/_app/channels/livechat': typeof AppChannelsLivechatRoute
  '/_app/channels/telegram': typeof AppChannelsTelegramRoute
  '/_app/channels/whatsapp': typeof AppChannelsWhatsappRouteWithChildren
  '/_app/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/developers/api-documentation': typeof AppDevelopersApiDocumentationRoute
  '/_app/developers/api-tools': typeof AppDevelopersApiToolsRouteWithChildren
  '/_app/developers/messages-sent-by-api': typeof AppDevelopersMessagesSentByApiRoute
  '/_app/developers/webhooks': typeof AppDevelopersWebhooksRoute
  '/_app/flows/$flowId': typeof AppFlowsFlowIdRoute
  '/_app/kelola-tim/$userId': typeof AppKelolaTimUserIdRoute
  '/_app/sakti/surat-baru': typeof AppSaktiSuratBaruRoute
  '/_app/sales-profiles/$userId': typeof AppSalesProfilesUserIdRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/alih-tugas/': typeof AppAlihTugasIndexRoute
  '/_app/companies/': typeof AppCompaniesIndexRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/developers/': typeof AppDevelopersIndexRoute
  '/_app/kelola-tim/': typeof AppKelolaTimIndexRoute
  '/_app/sakti/': typeof AppSaktiIndexRoute
  '/_app/sales-profiles/': typeof AppSalesProfilesIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
  '/_app/channels/whatsapp/$channelId': typeof AppChannelsWhatsappChannelIdRoute
  '/_app/channels/whatsapp/success': typeof AppChannelsWhatsappSuccessRoute
  '/_app/developers/api-tools/new': typeof AppDevelopersApiToolsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/ai'
    | '/ai-agents'
    | '/analytics'
    | '/broadcast'
    | '/chat'
    | '/dashboard'
    | '/deals'
    | '/flows'
    | '/handover'
    | '/help'
    | '/import'
    | '/integration'
    | '/knowledge'
    | '/log-aktivitas'
    | '/metrics'
    | '/notifikasi'
    | '/opportunity'
    | '/pipeline'
    | '/prospek'
    | '/settings'
    | '/templates'
    | '/whatsapp/connect'
    | '/ai-agents/$agentId'
    | '/alih-tugas/$conversationId'
    | '/apps/meta-ads-tracker'
    | '/channels/bot'
    | '/channels/custom'
    | '/channels/facebook'
    | '/channels/line'
    | '/channels/livechat'
    | '/channels/telegram'
    | '/channels/whatsapp'
    | '/companies/$companyId'
    | '/customers/$customerId'
    | '/developers/api-documentation'
    | '/developers/api-tools'
    | '/developers/messages-sent-by-api'
    | '/developers/webhooks'
    | '/flows/$flowId'
    | '/kelola-tim/$userId'
    | '/sakti/surat-baru'
    | '/sales-profiles/$userId'
    | '/tasks/$taskId'
    | '/alih-tugas/'
    | '/companies/'
    | '/customers/'
    | '/developers/'
    | '/kelola-tim/'
    | '/sakti/'
    | '/sales-profiles/'
    | '/tasks/'
    | '/channels/whatsapp/$channelId'
    | '/channels/whatsapp/success'
    | '/developers/api-tools/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/ai'
    | '/ai-agents'
    | '/analytics'
    | '/broadcast'
    | '/chat'
    | '/dashboard'
    | '/deals'
    | '/flows'
    | '/handover'
    | '/help'
    | '/import'
    | '/integration'
    | '/knowledge'
    | '/log-aktivitas'
    | '/metrics'
    | '/notifikasi'
    | '/opportunity'
    | '/pipeline'
    | '/prospek'
    | '/settings'
    | '/templates'
    | '/whatsapp/connect'
    | '/ai-agents/$agentId'
    | '/alih-tugas/$conversationId'
    | '/apps/meta-ads-tracker'
    | '/channels/bot'
    | '/channels/custom'
    | '/channels/facebook'
    | '/channels/line'
    | '/channels/livechat'
    | '/channels/telegram'
    | '/channels/whatsapp'
    | '/companies/$companyId'
    | '/customers/$customerId'
    | '/developers/api-documentation'
    | '/developers/api-tools'
    | '/developers/messages-sent-by-api'
    | '/developers/webhooks'
    | '/flows/$flowId'
    | '/kelola-tim/$userId'
    | '/sakti/surat-baru'
    | '/sales-profiles/$userId'
    | '/tasks/$taskId'
    | '/alih-tugas'
    | '/companies'
    | '/customers'
    | '/developers'
    | '/kelola-tim'
    | '/sakti'
    | '/sales-profiles'
    | '/tasks'
    | '/channels/whatsapp/$channelId'
    | '/channels/whatsapp/success'
    | '/developers/api-tools/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/_app/ai'
    | '/_app/ai-agents'
    | '/_app/analytics'
    | '/_app/broadcast'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/deals'
    | '/_app/flows'
    | '/_app/handover'
    | '/_app/help'
    | '/_app/import'
    | '/_app/integration'
    | '/_app/knowledge'
    | '/_app/log-aktivitas'
    | '/_app/metrics'
    | '/_app/notifikasi'
    | '/_app/opportunity'
    | '/_app/pipeline'
    | '/_app/prospek'
    | '/_app/settings'
    | '/_app/templates'
    | '/whatsapp/connect'
    | '/_app/ai-agents/$agentId'
    | '/_app/alih-tugas/$conversationId'
    | '/_app/apps/meta-ads-tracker'
    | '/_app/channels/bot'
    | '/_app/channels/custom'
    | '/_app/channels/facebook'
    | '/_app/channels/line'
    | '/_app/channels/livechat'
    | '/_app/channels/telegram'
    | '/_app/channels/whatsapp'
    | '/_app/companies/$companyId'
    | '/_app/customers/$customerId'
    | '/_app/developers/api-documentation'
    | '/_app/developers/api-tools'
    | '/_app/developers/messages-sent-by-api'
    | '/_app/developers/webhooks'
    | '/_app/flows/$flowId'
    | '/_app/kelola-tim/$userId'
    | '/_app/sakti/surat-baru'
    | '/_app/sales-profiles/$userId'
    | '/_app/tasks/$taskId'
    | '/_app/alih-tugas/'
    | '/_app/companies/'
    | '/_app/customers/'
    | '/_app/developers/'
    | '/_app/kelola-tim/'
    | '/_app/sakti/'
    | '/_app/sales-profiles/'
    | '/_app/tasks/'
    | '/_app/channels/whatsapp/$channelId'
    | '/_app/channels/whatsapp/success'
    | '/_app/developers/api-tools/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  WhatsappConnectRoute: typeof WhatsappConnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/connect': {
      id: '/whatsapp/connect'
      path: '/whatsapp/connect'
      fullPath: '/whatsapp/connect'
      preLoaderRoute: typeof WhatsappConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prospek': {
      id: '/_app/prospek'
      path: '/prospek'
      fullPath: '/prospek'
      preLoaderRoute: typeof AppProspekRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunity': {
      id: '/_app/opportunity'
      path: '/opportunity'
      fullPath: '/opportunity'
      preLoaderRoute: typeof AppOpportunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifikasi': {
      id: '/_app/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof AppNotifikasiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/log-aktivitas': {
      id: '/_app/log-aktivitas'
      path: '/log-aktivitas'
      fullPath: '/log-aktivitas'
      preLoaderRoute: typeof AppLogAktivitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge': {
      id: '/_app/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integration': {
      id: '/_app/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof AppIntegrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/handover': {
      id: '/_app/handover'
      path: '/handover'
      fullPath: '/handover'
      preLoaderRoute: typeof AppHandoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flows': {
      id: '/_app/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof AppFlowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deals': {
      id: '/_app/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof AppDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broadcast': {
      id: '/_app/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof AppBroadcastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-agents': {
      id: '/_app/ai-agents'
      path: '/ai-agents'
      fullPath: '/ai-agents'
      preLoaderRoute: typeof AppAiAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-profiles/': {
      id: '/_app/sales-profiles/'
      path: '/sales-profiles'
      fullPath: '/sales-profiles/'
      preLoaderRoute: typeof AppSalesProfilesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sakti/': {
      id: '/_app/sakti/'
      path: '/sakti'
      fullPath: '/sakti/'
      preLoaderRoute: typeof AppSaktiIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-tim/': {
      id: '/_app/kelola-tim/'
      path: '/kelola-tim'
      fullPath: '/kelola-tim/'
      preLoaderRoute: typeof AppKelolaTimIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/': {
      id: '/_app/developers/'
      path: '/developers'
      fullPath: '/developers/'
      preLoaderRoute: typeof AppDevelopersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies/': {
      id: '/_app/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AppCompaniesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alih-tugas/': {
      id: '/_app/alih-tugas/'
      path: '/alih-tugas'
      fullPath: '/alih-tugas/'
      preLoaderRoute: typeof AppAlihTugasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-profiles/$userId': {
      id: '/_app/sales-profiles/$userId'
      path: '/sales-profiles/$userId'
      fullPath: '/sales-profiles/$userId'
      preLoaderRoute: typeof AppSalesProfilesUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sakti/surat-baru': {
      id: '/_app/sakti/surat-baru'
      path: '/sakti/surat-baru'
      fullPath: '/sakti/surat-baru'
      preLoaderRoute: typeof AppSaktiSuratBaruRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kelola-tim/$userId': {
      id: '/_app/kelola-tim/$userId'
      path: '/kelola-tim/$userId'
      fullPath: '/kelola-tim/$userId'
      preLoaderRoute: typeof AppKelolaTimUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flows/$flowId': {
      id: '/_app/flows/$flowId'
      path: '/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof AppFlowsFlowIdRouteImport
      parentRoute: typeof AppFlowsRoute
    }
    '/_app/developers/webhooks': {
      id: '/_app/developers/webhooks'
      path: '/developers/webhooks'
      fullPath: '/developers/webhooks'
      preLoaderRoute: typeof AppDevelopersWebhooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/messages-sent-by-api': {
      id: '/_app/developers/messages-sent-by-api'
      path: '/developers/messages-sent-by-api'
      fullPath: '/developers/messages-sent-by-api'
      preLoaderRoute: typeof AppDevelopersMessagesSentByApiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/api-tools': {
      id: '/_app/developers/api-tools'
      path: '/developers/api-tools'
      fullPath: '/developers/api-tools'
      preLoaderRoute: typeof AppDevelopersApiToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/api-documentation': {
      id: '/_app/developers/api-documentation'
      path: '/developers/api-documentation'
      fullPath: '/developers/api-documentation'
      preLoaderRoute: typeof AppDevelopersApiDocumentationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies/$companyId': {
      id: '/_app/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AppCompaniesCompanyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/whatsapp': {
      id: '/_app/channels/whatsapp'
      path: '/channels/whatsapp'
      fullPath: '/channels/whatsapp'
      preLoaderRoute: typeof AppChannelsWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/telegram': {
      id: '/_app/channels/telegram'
      path: '/channels/telegram'
      fullPath: '/channels/telegram'
      preLoaderRoute: typeof AppChannelsTelegramRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/livechat': {
      id: '/_app/channels/livechat'
      path: '/channels/livechat'
      fullPath: '/channels/livechat'
      preLoaderRoute: typeof AppChannelsLivechatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/line': {
      id: '/_app/channels/line'
      path: '/channels/line'
      fullPath: '/channels/line'
      preLoaderRoute: typeof AppChannelsLineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/facebook': {
      id: '/_app/channels/facebook'
      path: '/channels/facebook'
      fullPath: '/channels/facebook'
      preLoaderRoute: typeof AppChannelsFacebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/custom': {
      id: '/_app/channels/custom'
      path: '/channels/custom'
      fullPath: '/channels/custom'
      preLoaderRoute: typeof AppChannelsCustomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channels/bot': {
      id: '/_app/channels/bot'
      path: '/channels/bot'
      fullPath: '/channels/bot'
      preLoaderRoute: typeof AppChannelsBotRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/meta-ads-tracker': {
      id: '/_app/apps/meta-ads-tracker'
      path: '/apps/meta-ads-tracker'
      fullPath: '/apps/meta-ads-tracker'
      preLoaderRoute: typeof AppAppsMetaAdsTrackerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alih-tugas/$conversationId': {
      id: '/_app/alih-tugas/$conversationId'
      path: '/alih-tugas/$conversationId'
      fullPath: '/alih-tugas/$conversationId'
      preLoaderRoute: typeof AppAlihTugasConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-agents/$agentId': {
      id: '/_app/ai-agents/$agentId'
      path: '/$agentId'
      fullPath: '/ai-agents/$agentId'
      preLoaderRoute: typeof AppAiAgentsAgentIdRouteImport
      parentRoute: typeof AppAiAgentsRoute
    }
    '/_app/developers/api-tools/new': {
      id: '/_app/developers/api-tools/new'
      path: '/new'
      fullPath: '/developers/api-tools/new'
      preLoaderRoute: typeof AppDevelopersApiToolsNewRouteImport
      parentRoute: typeof AppDevelopersApiToolsRoute
    }
    '/_app/channels/whatsapp/success': {
      id: '/_app/channels/whatsapp/success'
      path: '/success'
      fullPath: '/channels/whatsapp/success'
      preLoaderRoute: typeof AppChannelsWhatsappSuccessRouteImport
      parentRoute: typeof AppChannelsWhatsappRoute
    }
    '/_app/channels/whatsapp/$channelId': {
      id: '/_app/channels/whatsapp/$channelId'
      path: '/$channelId'
      fullPath: '/channels/whatsapp/$channelId'
      preLoaderRoute: typeof AppChannelsWhatsappChannelIdRouteImport
      parentRoute: typeof AppChannelsWhatsappRoute
    }
  }
}

interface AppAiAgentsRouteChildren {
  AppAiAgentsAgentIdRoute: typeof AppAiAgentsAgentIdRoute
}

const AppAiAgentsRouteChildren: AppAiAgentsRouteChildren = {
  AppAiAgentsAgentIdRoute: AppAiAgentsAgentIdRoute,
}

const AppAiAgentsRouteWithChildren = AppAiAgentsRoute._addFileChildren(
  AppAiAgentsRouteChildren,
)

interface AppFlowsRouteChildren {
  AppFlowsFlowIdRoute: typeof AppFlowsFlowIdRoute
}

const AppFlowsRouteChildren: AppFlowsRouteChildren = {
  AppFlowsFlowIdRoute: AppFlowsFlowIdRoute,
}

const AppFlowsRouteWithChildren = AppFlowsRoute._addFileChildren(
  AppFlowsRouteChildren,
)

interface AppChannelsWhatsappRouteChildren {
  AppChannelsWhatsappChannelIdRoute: typeof AppChannelsWhatsappChannelIdRoute
  AppChannelsWhatsappSuccessRoute: typeof AppChannelsWhatsappSuccessRoute
}

const AppChannelsWhatsappRouteChildren: AppChannelsWhatsappRouteChildren = {
  AppChannelsWhatsappChannelIdRoute: AppChannelsWhatsappChannelIdRoute,
  AppChannelsWhatsappSuccessRoute: AppChannelsWhatsappSuccessRoute,
}

const AppChannelsWhatsappRouteWithChildren =
  AppChannelsWhatsappRoute._addFileChildren(AppChannelsWhatsappRouteChildren)

interface AppDevelopersApiToolsRouteChildren {
  AppDevelopersApiToolsNewRoute: typeof AppDevelopersApiToolsNewRoute
}

const AppDevelopersApiToolsRouteChildren: AppDevelopersApiToolsRouteChildren = {
  AppDevelopersApiToolsNewRoute: AppDevelopersApiToolsNewRoute,
}

const AppDevelopersApiToolsRouteWithChildren =
  AppDevelopersApiToolsRoute._addFileChildren(
    AppDevelopersApiToolsRouteChildren,
  )

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAiAgentsRoute: typeof AppAiAgentsRouteWithChildren
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBroadcastRoute: typeof AppBroadcastRoute
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDealsRoute: typeof AppDealsRoute
  AppFlowsRoute: typeof AppFlowsRouteWithChildren
  AppHandoverRoute: typeof AppHandoverRoute
  AppHelpRoute: typeof AppHelpRoute
  AppImportRoute: typeof AppImportRoute
  AppIntegrationRoute: typeof AppIntegrationRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLogAktivitasRoute: typeof AppLogAktivitasRoute
  AppMetricsRoute: typeof AppMetricsRoute
  AppNotifikasiRoute: typeof AppNotifikasiRoute
  AppOpportunityRoute: typeof AppOpportunityRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppProspekRoute: typeof AppProspekRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppAlihTugasConversationIdRoute: typeof AppAlihTugasConversationIdRoute
  AppAppsMetaAdsTrackerRoute: typeof AppAppsMetaAdsTrackerRoute
  AppChannelsBotRoute: typeof AppChannelsBotRoute
  AppChannelsCustomRoute: typeof AppChannelsCustomRoute
  AppChannelsFacebookRoute: typeof AppChannelsFacebookRoute
  AppChannelsLineRoute: typeof AppChannelsLineRoute
  AppChannelsLivechatRoute: typeof AppChannelsLivechatRoute
  AppChannelsTelegramRoute: typeof AppChannelsTelegramRoute
  AppChannelsWhatsappRoute: typeof AppChannelsWhatsappRouteWithChildren
  AppCompaniesCompanyIdRoute: typeof AppCompaniesCompanyIdRoute
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppDevelopersApiDocumentationRoute: typeof AppDevelopersApiDocumentationRoute
  AppDevelopersApiToolsRoute: typeof AppDevelopersApiToolsRouteWithChildren
  AppDevelopersMessagesSentByApiRoute: typeof AppDevelopersMessagesSentByApiRoute
  AppDevelopersWebhooksRoute: typeof AppDevelopersWebhooksRoute
  AppKelolaTimUserIdRoute: typeof AppKelolaTimUserIdRoute
  AppSaktiSuratBaruRoute: typeof AppSaktiSuratBaruRoute
  AppSalesProfilesUserIdRoute: typeof AppSalesProfilesUserIdRoute
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppAlihTugasIndexRoute: typeof AppAlihTugasIndexRoute
  AppCompaniesIndexRoute: typeof AppCompaniesIndexRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppDevelopersIndexRoute: typeof AppDevelopersIndexRoute
  AppKelolaTimIndexRoute: typeof AppKelolaTimIndexRoute
  AppSaktiIndexRoute: typeof AppSaktiIndexRoute
  AppSalesProfilesIndexRoute: typeof AppSalesProfilesIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAiAgentsRoute: AppAiAgentsRouteWithChildren,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBroadcastRoute: AppBroadcastRoute,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDealsRoute: AppDealsRoute,
  AppFlowsRoute: AppFlowsRouteWithChildren,
  AppHandoverRoute: AppHandoverRoute,
  AppHelpRoute: AppHelpRoute,
  AppImportRoute: AppImportRoute,
  AppIntegrationRoute: AppIntegrationRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLogAktivitasRoute: AppLogAktivitasRoute,
  AppMetricsRoute: AppMetricsRoute,
  AppNotifikasiRoute: AppNotifikasiRoute,
  AppOpportunityRoute: AppOpportunityRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppProspekRoute: AppProspekRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppAlihTugasConversationIdRoute: AppAlihTugasConversationIdRoute,
  AppAppsMetaAdsTrackerRoute: AppAppsMetaAdsTrackerRoute,
  AppChannelsBotRoute: AppChannelsBotRoute,
  AppChannelsCustomRoute: AppChannelsCustomRoute,
  AppChannelsFacebookRoute: AppChannelsFacebookRoute,
  AppChannelsLineRoute: AppChannelsLineRoute,
  AppChannelsLivechatRoute: AppChannelsLivechatRoute,
  AppChannelsTelegramRoute: AppChannelsTelegramRoute,
  AppChannelsWhatsappRoute: AppChannelsWhatsappRouteWithChildren,
  AppCompaniesCompanyIdRoute: AppCompaniesCompanyIdRoute,
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppDevelopersApiDocumentationRoute: AppDevelopersApiDocumentationRoute,
  AppDevelopersApiToolsRoute: AppDevelopersApiToolsRouteWithChildren,
  AppDevelopersMessagesSentByApiRoute: AppDevelopersMessagesSentByApiRoute,
  AppDevelopersWebhooksRoute: AppDevelopersWebhooksRoute,
  AppKelolaTimUserIdRoute: AppKelolaTimUserIdRoute,
  AppSaktiSuratBaruRoute: AppSaktiSuratBaruRoute,
  AppSalesProfilesUserIdRoute: AppSalesProfilesUserIdRoute,
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppAlihTugasIndexRoute: AppAlihTugasIndexRoute,
  AppCompaniesIndexRoute: AppCompaniesIndexRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppDevelopersIndexRoute: AppDevelopersIndexRoute,
  AppKelolaTimIndexRoute: AppKelolaTimIndexRoute,
  AppSaktiIndexRoute: AppSaktiIndexRoute,
  AppSalesProfilesIndexRoute: AppSalesProfilesIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  WhatsappConnectRoute: WhatsappConnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
